kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: environnement
    commands:
      - ls -la /home/tonycava/cloned_repo/
      - cp /home/tonycava/cloned_repo/discution-app-front/.env .

  - name: build
    commands:
      - docker build -t koomei:front .

  - name: stop-previous-version
    commands:
      - docker rm -f koomei-front || true

  - name: deploy
    commands:
      - make deploy
